### NUMPY QUESTIONS

### Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
import numpy as np

A = np.random.randint(1, 21, size=(5,5))
A[::,2] = 1
print(A)

print()

B = np.random.randint(1, 17, size=(4,4))
np.fill_diagonal(B, 1)
print(B)

[[ 9  2  1 20 16]
 [ 6 12  1 15 13]
 [ 2  3  1  3  8]
 [12 11  1  7  5]
 [ 7 19  1  2 14]]

[[ 1 16 12  6]
 [11  1  4 15]
 [15 10  1  8]
 [ 8 10  6  1]]


### Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
import numpy as np

A = np.random.randint(1, 37, size=(6,6))
sub_A = A[2:5:, 1:4:]
print(A)
print()
print(sub_A)

[[ 8 24 21 33 30 30]
 [ 4 16 27  4 31 28]
 [23 26  3 28  4 33]
 [30 35 18 14 30 25]
 [16 33  6 36 16 16]
 [ 8 28 23 21 36 16]]

[[26  3 28]
 [35 18 14]
 [33  6 36]]


In [24]:
import numpy as np

A = np.random.randint(1, 37, size=(5,5))
print(A)
print()


arr = np.concatenate((A[0,:], A[-1,:], A[1:4, 0], A[1:4, -1]))
print(arr)

[[ 8 14 28  3 25]
 [32 35 15 34 33]
 [33 23 30 34  8]
 [35 30  3 18 34]
 [10 34 24 11 28]]

[ 8 14 28  3 25 10 34 24 11 28 32 33 35 33  8 34]


### Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [27]:
import numpy as np

arr1 = np.random.randint(1, 36, size=(3, 4))
arr2 = np.random.randint(1, 36, size=(3, 4))
print(arr1)
print(arr2)

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[ 8 29 24 10]
 [ 7 22 27 35]
 [ 7 10 26 21]]
[[ 6 33 22 24]
 [17  6 12  7]
 [27 29  6 28]]
[[14 62 46 34]
 [24 28 39 42]
 [34 39 32 49]]
[[  2  -4   2 -14]
 [-10  16  15  28]
 [-20 -19  20  -7]]
[[ 48 957 528 240]
 [119 132 324 245]
 [189 290 156 588]]
[[1.33333333 0.87878788 1.09090909 0.41666667]
 [0.41176471 3.66666667 2.25       5.        ]
 [0.25925926 0.34482759 4.33333333 0.75      ]]


In [31]:
import numpy as np

arr = np.random.randint(1, 10, size=(4, 4))
print(arr)
print()

row_sum = np.sum(arr, axis=1)
print(row_sum)

col_sum = np.sum(arr, axis=0)
print(col_sum)

[[4 6 5 1]
 [1 9 4 9]
 [6 5 4 3]
 [4 1 3 1]]

[16 23 18  9]
[15 21 16 14]


### Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [36]:
arr = np.random.randint(1, 10, size=(5, 5))

print("Mean", np.mean(arr))
print("Median", np.median(arr))
print("Standard deviation", np.std(arr))
print("Variance", np.var(arr))

Mean 4.96
Median 5.0
Standard deviation 2.7199999999999998
Variance 7.398399999999999


### Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [40]:
arr = np.random.randint(1, 10, size=(3, 3))
arr1 = np.random.randint(1, 10, size=(3,))

print(arr)
print()
print(arr1)
print()
print(arr + arr1)

[[7 5 9]
 [4 9 4]
 [5 2 2]]

[5 3 8]

[[12  8 17]
 [ 9 12 12]
 [10  5 10]]


In [50]:
arr = np.random.randint(1, 10, size=(4, 4))
arr1 = np.random.randint(1, 10, size=(4,))

#print(arr1[:, np.newaxis]) 

arr2 = arr1.reshape(4,1)
print(arr2)

print(arr)
print(arr1)

print()

print("ANS", arr-arr2)

[[4]
 [8]
 [2]
 [4]]
[[4 5 4 5]
 [6 3 4 2]
 [7 5 6 8]
 [7 3 4 9]]
[4 8 2 4]

ANS [[ 0  1  0  1]
 [-2 -5 -4 -6]
 [ 5  3  4  6]
 [ 3 -1  0  5]]


### Linear Algebra

1. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [52]:
arr = np.random.randint(1, 10, size=(2,3))
arr1 = np.random.randint(1, 10, size=(3,2))

print(np.dot(arr, arr1))

[[ 19  76]
 [ 38 102]]


### Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [54]:
arr = np.random.randint(1, 10, size=(3,3))

print(arr.reshape(1,9))
print(arr.reshape(9,1))

[[7 2 2 5 9 1 2 8 2]]
[[7]
 [2]
 [2]
 [5]
 [9]
 [1]
 [2]
 [8]
 [2]]


In [58]:
arr = np.random.randint(1, 10, size=(5,5))

arr_flatten = arr.flatten()
print(arr_flatten)

arr_reshape = arr_flatten.reshape(5, 5)
print(arr_reshape)

[1 8 5 4 2 4 9 6 7 2 7 6 5 8 3 1 1 7 4 8 3 6 8 6 6]
[[1 8 5 4 2]
 [4 9 6 7 2]
 [7 6 5 8 3]
 [1 1 7 4 8]
 [3 6 8 6 6]]


### **Boolean Indexing**

1. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [60]:
arr = np.random.randint(1, 30, size=(5,5))
print(arr)
arr[arr>10] = 10
print()
print(arr)

[[21  1 15  6 16]
 [26  4 15  3 25]
 [ 3 26  3 28  9]
 [12  8 27 11 11]
 [ 5 14 12  7 18]]

[[10  1 10  6 10]
 [10  4 10  3 10]
 [ 3 10  3 10  9]
 [10  8 10 10 10]
 [ 5 10 10  7 10]]
