### 1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.


In [13]:
import numpy as np

arr = np.random.randint(1, 10, size=(5,))
arr2 = np.random.randint(1, 10, size=(5,4))
arr3 = np.random.randint(1, 10, size=(3,3,3))

print(arr.ndim)
print(arr.shape)
print(arr2.ndim)
print(arr2.shape)
print(arr3.ndim)
print(arr3.shape)

1
(5,)
2
(5, 4)
3
(3, 3, 3)


### 2 . Create:
an array of zeros of shape (3,3)


an array of ones of shape (2,5)


an array filled with 7


In [18]:
import numpy as np

arr = np.zeros((3,3))
arr2 = np.ones((2,5))

print(arr)
print(arr2)

arr3 = np.full((3,3), 7)
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


### 3 . Create an array of even numbers between 10 and 50 using arange.


In [37]:
import numpy as np

arr = np.arange(10, 50, 2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


### 4 . Create a 4×4 matrix from 0–15. Then , extract:

In [34]:
import numpy as np

arr = np.random.randint(0, 16, size=(4,4))

first_row = arr[0,:]
last_col = arr[::,-1]
two_two = arr[1:3, 1:3]

print(first_row)
print(last_col)
print(two_two)

[ 9  5 13  4]
[4 1 8 7]
[[ 0  4]
 [13  8]]


### 5 . Add a 1D array [1,2,3] to each row of a 3×3 matrix.


In [36]:
import numpy as np

arr = np.random.randint(1, 10, size=(3,3))

arr2 = np.array([1,2,3])

add_arr = arr+arr2
print(add_arr)

[[ 8  7 12]
 [ 9  4 10]
 [ 5  6  9]]


### 6 . Given two arrays A and B, compute:
(A + B) / 2


A^2 + B^2



In [38]:
import numpy as np

arr = np.random.randint(1, 10, size=(3,3))
arr2 = np.random.randint(1, 10, size=(3,3))

print((arr+arr2)/2)
print(arr**2 + arr2**2)

[[6.5 5.5 7. ]
 [3.5 5.  7. ]
 [4.  3.5 5.5]]
[[ 85  85 100]
 [ 29  82 106]
 [ 50  37  61]]
