## Numpy Array Manipulation

In [5]:
import numpy as np

arr = np.random.randint(1, 100, size=(5,10))   # sample-5, features-10

print(arr.shape)

b = arr.reshape(10, 5)   #reshape size must be the multiplication value of the previous. like 5x10 = 10x5 or 5x10 = 25x2

print(b.shape)

(5, 10)
(10, 5)


In [10]:
# flatten()     #converts into 1d

import numpy as np

arr = np.random.randint(1, 100, size=(5,10))   # sample-5, features-10

b = arr.reshape(10, 5)   #reshape size must be the multiplication value of the previous. like 5x10 = 10x5 or 5x10 = 25x2

print(b)

print(b.shape)
print(b.ndim)

flatten = b.flatten()
print(flatten)   # row wise 1d combined

[[65 98 97 91 68]
 [62 82 74 97 87]
 [97 77 60 29 36]
 [16 14 31 56 86]
 [57 17 46 86 10]
 [66 72 23 96 52]
 [90 61 18 52 81]
 [28 19 71 67 44]
 [58 92 12 59 92]
 [36 47 33 61 51]]
(10, 5)
2
[65 98 97 91 68 62 82 74 97 87 97 77 60 29 36 16 14 31 56 86 57 17 46 86
 10 66 72 23 96 52 90 61 18 52 81 28 19 71 67 44 58 92 12 59 92 36 47 33
 61 51]


In [14]:
# column wise flattening
# ravel()

import numpy as np

arr = np.random.randint(1, 100, size=(5,10))   # sample-5, features-10

b = arr.reshape(10, 5)   #reshape size must be the multiplication value of the previous. like 5x10 = 10x5 or 5x10 = 25x2

print(b.shape)
print(b.ndim)

print(b)

col_wise_flattening = np.ravel(b, order='F')
print(col_wise_flattening)

(10, 5)
2
[[87 92 51 17  3]
 [35 68 81 50  9]
 [79 56 18  9 10]
 [35 12 34  6 16]
 [59 77 50 45 67]
 [83 37 45  1 38]
 [ 3 59 40 28 44]
 [87 23 29 60 33]
 [29 82 20 61 53]
 [46 14 49 52  7]]
[87 35 79 35 59 83  3 87 29 46 92 68 56 12 77 37 59 23 82 14 51 81 18 34
 50 45 40 29 20 49 17 50  9  6 45  1 28 60 61 52  3  9 10 16 67 38 44 33
 53  7]


In [17]:
# row wise flattening
# ravel()  

import numpy as np

arr = np.random.randint(1, 100, size=(5,10))   # sample-5, features-10

b = arr.reshape(10, 5)   #reshape size must be the multiplication value of the previous. like 5x10 = 10x5 or 5x10 = 25x2

print(b.shape)
print(b.ndim)

print(b)

row_wise_flattening = np.ravel(b, order='C')
print(row_wise_flattening)

(10, 5)
2
[[87 27 10 13 50]
 [25 47 47 93 44]
 [23 67 66 71 28]
 [70 32 85 35 77]
 [92 69  3  6 55]
 [ 9 61 99  4 13]
 [69 94 34 33 26]
 [77 22 97 55 79]
 [92 62 13 38 47]
 [23 44 15 82 81]]
[87 27 10 13 50 25 47 47 93 44 23 67 66 71 28 70 32 85 35 77 92 69  3  6
 55  9 61 99  4 13 69 94 34 33 26 77 22 97 55 79 92 62 13 38 47 23 44 15
 82 81]


### Concatenate

In [20]:
# np.concatenate((array1, array2), axis=?)

a = np.random.randint(1, 10, size=(2,3))
b = np.random.randint(20, 30, size=(2,3))

print(a)
print(b)

print("\n")

con_row = np.concatenate((a,b), axis=0) #row wise

print(con_row)

[[8 3 8]
 [4 2 3]]
[[23 24 21]
 [20 24 25]]


[[ 8  3  8]
 [ 4  2  3]
 [23 24 21]
 [20 24 25]]


In [22]:
# np.concatenate((array1, array2), axis=?)

a = np.random.randint(1, 10, size=(2,3))
b = np.random.randint(20, 30, size=(2,3))

print(a)
print(b)

print("\n")

con_col = np.concatenate((a,b), axis=1) #col_wise

print(con_col)

[[4 2 3]
 [7 1 6]]
[[22 23 20]
 [24 20 25]]


[[ 4  2  3 22 23 20]
 [ 7  1  6 24 20 25]]


In [ ]:
### Column wise concatenate -> row must be same
### Row wise concatenate -> Col must be same

In [24]:
# error

x = np.random.randint(1, 10, size=(2,3))
y = np.random.randint(20, 30, size=(1,3))

r = np.concatenate((x,y), axis=0)

print(r)

[[ 6  9  4]
 [ 5  3  1]
 [21 22 21]]


In [25]:
# error

x = np.random.randint(1, 10, size=(2,3))
y = np.random.randint(20, 30, size=(1,3))

r = np.concatenate((x,y), axis=1)

print(r)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [27]:
#transpose

mat = np.array([[10,20,30], [40,50,60]])

transpose = mat.T

print(transpose)

[[10 40]
 [20 50]
 [30 60]]


In [29]:
mat = np.array([[10,20,30]])

transpose = mat.T

print(transpose)

[[10]
 [20]
 [30]]


In [32]:
#array split

# np.array_split(array, size_to_divide)


a = np.random.randint(1, 10, size=(10,))
print(a)

splitted_array = np.array_split(a, 3)

print(splitted_array)

[9 2 6 9 1 4 3 4 6 5]
[array([9, 2, 6, 9], dtype=int32), array([1, 4, 3], dtype=int32), array([4, 6, 5], dtype=int32)]


In [34]:
a = np.random.randint(1, 10, size=(10,))
print(a)

splitted_array = np.split(a, 3)

print(splitted_array)
#equal division

[6 8 4 2 7 6 2 4 6 7]


ValueError: array split does not result in an equal division

In [38]:
# addition to col values

# faster for vectorization

x = np.array([10, 20, 30, 40])
y = np.array([2, 3, 4, 5])

add = x + y    # np.add(x,y)
print(add)

sub = x-y
print(sub)

mult = x * y
print(mult)

div = x / y
print(div)

rem = x % y
print(rem)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


### Mathematical Function

In [45]:
# trigonometry

x = np.array([10, 20, 30, 40])
#sin, cos, tan takes values in radian

sin_val = np.sin(x)

print(sin_val)

cos_val = np.cos(x)
print(cos_val)

tan_val = np.tan(x)
print(tan_val)


# Convert from radian to degree

deg_con = np.rad2deg(x)
print(deg_con)

#deg2rad

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]


In [47]:
# log (logarithm)

x = np.array([10, 20, 30, 40])

base_10_log_val = np.log10(x)   #10 diye koybar vaag kra jabe
print(base_10_log_val)

base_2_log_val = np.log2(x)
print(base_2_log_val)

[1.         1.30103    1.47712125 1.60205999]
[3.32192809 4.32192809 4.9068906  5.32192809]


In [51]:
# sqrt (square root)
x = np.array([2, 4, 30, 16])

sqrt = np.sqrt(x)

print(sqrt)

[1.41421356 2.         5.47722558 4.        ]


In [55]:
#sum

x = np.array([2, 2, 2, 2])

summation = np.sum(x)

print(summation)

8


In [56]:
#cumulative sum
x = np.array([2, 4, 30, 16])

cuMul = np.cumulative_sum(x)
print(cuMul)

[ 2  6 36 52]


### numpy Broadcasting

In [58]:
x = np.array([2, 4, 30, 16])

result = x ** 2    # [2  2 2 2 2]
print(result)

[  4  16 900 256]


In [59]:
x = np.array([2, 4, 30, 16])

result = x + 2
print(result)

[ 4  6 32 18]


In [61]:
mat = np.array([[10, 20, 30], [40, 50, 60]])

result = mat + 2
print(result)

[[12 22 32]
 [42 52 62]]


In [65]:
mat = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])

#matrix column size and vector column size must be same
result = mat + vector    #[1 2 3
                         # 1 2 3]
print(result)

[[11 22 33]
 [41 52 63]]


### Logical Functions

In [68]:
#comparison >, <, >=, <=, ==, !=

x = np.array([10, 20, 30, 40])
y = np.array([2, 3, 4, 5])

greater_than = x > y
print(greater_than)

equal = x==y
print(equal)

print(np.all(greater_than)) # if all true, returns True
print(np.any(equal)) # if one True, returns True

[ True  True  True  True]
[False False False False]
True
False


### Ndarray Sorting

In [1]:
# arr.sort()
import numpy as np

x = np.array([56, 2, 60, 19, 92])

z = x.copy()
print(z)

z.sort() #inplace sorting
print(z)

[56  2 60 19 92]
[ 2 19 56 60 92]


In [72]:
# copy sorting
# np.sort(arr)

x = np.array([56, 2, 60, 19, 92])

sort_arr = np.sort(x)

print(sort_arr)
print(x)

[ 2 19 56 60 92]
[56  2 60 19 92]


In [74]:
#2d array sorting

#horizontal sorting

mat = np.array([[10, 3, 5], [8, 4, 9]])

hor_sort = np.sort(mat, axis=1)
print(hor_sort)

[[ 3  5 10]
 [ 4  8  9]]


In [12]:
#vertical sorting

mat = np.array([[10, 3, 5], [8, 4, 9]])

hor_sort = np.sort(mat, axis=0)
print(hor_sort)

[[ 8  3  5]
 [10  4  9]]


### Ndarray Searching

In [76]:
# np.where()
x = np.array([56, 2, 60, 19, 92])

index = np.where(x==60)
print(index)

(array([2]),)


In [77]:
x = np.array([56, 2, 60, 19, 92])

index = np.where(x>19)
print(index)

(array([0, 2, 4]),)


In [4]:
# change the greater values to 0

# np.where(condition, x, y) if true x, else replace with y

x = np.array([56, 2, 60, 19, 92])

arr = np.where(x>19, x, 0)
print(arr)

[56  0 60  0 92]


In [6]:
mat = np.array([[10, 3, 5], [8, 4, 9]])

index = np.where(mat > 8)
print(index) # returnx x axis value first, then y axis

(array([0, 1]), array([0, 2]))


In [13]:
mat = np.array([[10, 3, 5], [8, 4, 9]])

arr = np.where(mat > 8, mat, 0)
print(arr)

[[10  0  0]
 [ 0  0  9]]


In [24]:
#counting

x = np.array([56, 2, 60, 92, 19])
print(x)
maximum_val_idx = np.argmax(x)
print(maximum_val_idx)
print(max(x))

[56  2 60 92 19]
3
92


In [23]:
x = np.array([56, 92, 2, 60, 92, 19])
maximum_val_idx = np.argmax(x) #returns first maximum index
print(maximum_val_idx)

1


In [22]:
x = np.array([56, 92, 2, 60, 92, 19])
minimum_val_idx = np.argmin(x) #returns first minimum index
print(minimum_val_idx)

2


### Counting

In [12]:
#count_nonzero

a = np.random.randint(1, 100, size=(100,))
print(a)

values_greater_than_60 = np.count_nonzero(a > 60)
print(values_greater_than_60)

values_equal_to_38 = np.count_nonzero(a == 38)
print(values_equal_to_38)

[20 39 23 92 76 11 77 51 64 17 84 85 53 33 97 11  9 45 61 38 83 53  8 57
 83 92 64 70 82 12  8 77  3 98 21 13 38 45 44 38 38 24 28 50 45 38 92 95
  6 78 73  8 22 22 11 35 87 58 76 15 38 92 73 22 84  8  7 15 85 70 17 70
 18 57 55  5 47 49  7 13 68 81 87 35 58  8 93 12 14 54 67 83  2 96 79 69
 82 57 31 57]
38
6


In [13]:
#unique

a = np.random.randint(1, 100, size=(100,))

unique_value = np.unique(a)
print(a)
print(unique_value)

print()
# how many unique values how many times
unique_value_with_counts = np.unique(a, return_counts=True)
print(unique_value_with_counts)

[11 78 40 49 60 70  7 71  3 90 98  4 87 75 52 77 73 78 10 93 20  3 97 47
 88 64 12  8 82 19 42 15 19 18  3 62 86 53 50 20 70 44 86 92 79 84 46 75
 63 35 40 58 52 86 97  3 50 97  4  1 88 88  8 11 43 96 29 44 72 76 95 38
 68 52 24 29 44 29 11 76 66 43 69 76 69 13 40 13 96  5 39 68 98 96 16 56
 27 17 81 76]
[ 1  3  4  5  7  8 10 11 12 13 15 16 17 18 19 20 24 27 29 35 38 39 40 42
 43 44 46 47 49 50 52 53 56 58 60 62 63 64 66 68 69 70 71 72 73 75 76 77
 78 79 81 82 84 86 87 88 90 92 93 95 96 97 98]

(array([ 1,  3,  4,  5,  7,  8, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 24,
       27, 29, 35, 38, 39, 40, 42, 43, 44, 46, 47, 49, 50, 52, 53, 56, 58,
       60, 62, 63, 64, 66, 68, 69, 70, 71, 72, 73, 75, 76, 77, 78, 79, 81,
       82, 84, 86, 87, 88, 90, 92, 93, 95, 96, 97, 98], dtype=int32), array([1, 4, 2, 1, 1, 2, 1, 3, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 3, 1, 1, 1,
       3, 1, 2, 3, 1, 1, 1, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1,
       1, 2, 4, 1, 2, 1, 1, 1, 1, 3, 1, 3, 1, 1, 1, 1, 3, 

In [14]:
# unpacking unique values

a = np.random.randint(1, 100, size=(100,))

unique_values, count = np.unique(a, return_counts=True)
print(unique_value)
print(count)

[ 1  3  4  5  7  8 10 11 12 13 15 16 17 18 19 20 24 27 29 35 38 39 40 42
 43 44 46 47 49 50 52 53 56 58 60 62 63 64 66 68 69 70 71 72 73 75 76 77
 78 79 81 82 84 86 87 88 90 92 93 95 96 97 98]
[1 1 1 1 1 1 2 2 2 2 1 1 1 3 1 2 2 1 1 2 1 2 1 1 2 2 1 1 1 1 3 2 1 2 1 1 2
 1 1 1 1 1 1 1 2 1 1 3 1 2 3 2 1 2 1 2 1 2 3 2 1 1 2 3 1 2]


### Statistical Function

In [28]:
data = np.genfromtxt('student_scores.csv', delimiter=',', skip_header=1)
print(data)

#min math marks
math_marks = data[::, :1]   # data[::, 0:1:]
print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

#standard deviation (diverse or close to avg marks)
std_math_marks = np.std(math_marks)
print(std_math_marks)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]
[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


### Linear Algebra

In [1]:
# Correlation coefficient 

import numpy as np

study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)
print(correlation)

[[1.         0.99859154]
 [0.99859154 1.        ]]


In [10]:
# matrix multiplication ( A's col and B's row must be same )

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12],
])

dot_product = np.dot(A, B)
print(dot_product)

print()

# trace ( sum of diag )
trace = np.trace(B)
print(trace)

#determinant ( must be square matrix )
C = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
deter = np.linalg.det(C)
print(deter)

print()


#rank of a matrix ( echelon and row echelon first )
rank_of_C = np.linalg.matrix_rank(C)
print(rank_of_C)

[[ 58  64]
 [139 154]]

17
6.66133814775094e-16

2


In [2]:
C = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

inverse = np.linalg.inv(C)
print(inverse)

[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
