### NUMPY

In [1]:
arr = [1, 2, 3]

print(arr*5)

arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])

print(arr1*5)

[ 5 10 15]


### Ndarray

In [10]:
import numpy as np

#1d array
arr1 = np.array([1, 2, 3, 4, 5])

print(type(arr1))
print(arr1)

print(arr1.ndim) #returns dimension of the array


#2d array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)
print(arr2.ndim)


#3d array
arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(arr3)
print(arr3.ndim)

<class 'numpy.ndarray'>
[1 2 3 4 5]
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


 ### Array Attributes

In [13]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr3 = np.array([
    #1st floor
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    #2nd floor
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

#dimension
print("Array Dimension", arr1.ndim)
print("Array Dimension", arr2.ndim)
print("Array Dimension", arr3.ndim)

#shape
print("Array shape", arr1.shape)
print("Array shape", arr2.shape)
print("Array shape", arr3.shape)

#data type
print("Array data type", arr1.dtype)
print("Array data type", arr2.dtype)
print("Array data type", arr3.dtype)

#size
print("Array size", arr1.size)
print("Array size", arr2.size)
print("Array size", arr3.size)

Array Dimension 1
Array Dimension 2
Array Dimension 3
Array shape (3,)
Array shape (3, 3)
Array shape (2, 2, 3)
Array data type int64
Array data type int64
Array data type int64
Array size 3
Array size 9
Array size 12


In [3]:
arr4 = np.array([1.2, 1.4, 2.6])
print(arr4.dtype)

float64


In [15]:
# upcasting
arr5 = np.array([1, 2, 3.2])
print(arr5.dtype)

arr6 = np.array([1, 2, 3.2, "2"])
print(arr6.dtype) # string upcasting

arr7 = np.array([1, 2, 3.2, "hello"])
print(arr7.dtype) # string upcasting
print(arr7)

float64
<U32
<U32
['1' '2' '3.2' 'hello']


### Selecting a data type for an array

In [9]:
arr8 = np.array([1, 2, 3], dtype=np.int8)
print(arr8.dtype)

int8


In [11]:
arr = np.array([1, 2, 3.2, "hello"], dtype=np.float64)
print(arr.dtype)
print(arr)

ValueError: could not convert string to float: 'hello'

In [12]:
arr = np.array([1, 2, 3])
arr = arr.astype(np.int16)
print(arr.dtype)

int16


In [16]:
lst = [10, 20, 30, 40, 40.5]

arr = np.array(lst, dtype=np.int32)
print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40 40]
<class 'numpy.ndarray'>
int32


In [17]:
lst = [10, 20, 30, 40, 40.5]

arr = np.array(lst)
print(arr)
print(type(arr))
print(arr.dtype)

[10.  20.  30.  40.  40.5]
<class 'numpy.ndarray'>
float64


In [18]:
mixed_lst = [10, True, "Hello", 10.5]

arr = np.array(mixed_lst)

print(arr)
print(type(arr))
print(arr.dtype)

['10' 'True' 'Hello' '10.5']
<class 'numpy.ndarray'>
<U32


In [19]:
mixed_lst = [10, True, "Hello", 10.5, [1, 5, 2]] # cannot provide another list inside list

arr = np.array(mixed_lst)

print(arr)
print(type(arr))
print(arr.dtype)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [21]:
matrix = [
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
]

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2


In [22]:
#tuple

tpl = (10, 20, 30)

arr = np.array(tpl)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1


In [23]:
st = {1, 2, 3} 

arr = np.array(st)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

{1, 2, 3}
<class 'numpy.ndarray'>
object
()
0


In [27]:
st = {1, 2, 3} 

arr = np.array(list(st))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


In [30]:
# dictionary

dc = {'a' : 10, 'b' : 20, 'c' : 30}

keys = dc.keys()

#keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1


In [33]:
dc = {'a' : 10, 'b' : 20, 'c' : 30}

values = dc.values()

#keys to ndarray
arr = np.array(list(values), dtype=np.float64)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10. 20. 30.]
<class 'numpy.ndarray'>
float64
(3,)
1


In [35]:
dc = {'a' : 10, 'b' : 20, 'c' : 30}

items = dc.items()

#keys to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2


### Ndarray creation from scratch

In [16]:
# np.zeros()

import numpy as np

arr = np.zeros((2, 3))  # row count, col count
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [15]:
arr = np.zeros((2, 3), dtype=np.int8)  # row count, col count
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6


In [14]:
arr = np.zeros((2, 3), dtype=np.int8)  # row count, col count

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6


In [13]:
# np.zeros_like()

arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

arr = np.zeros_like(arr3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
<class 'numpy.ndarray'>
int64
(2, 2, 3)
3
12


In [11]:
# np.ones()

arr = np.ones((2, 4)) # row count, col count
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>
float64
(2, 4)
2
8


In [17]:
arr = np.ones((3, 2, 4)) # floor count, row count, col count
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
<class 'numpy.ndarray'>
float64
(3, 2, 4)
3
24


In [18]:
# np.ones_like()

arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

arr = np.ones_like(arr3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int64
(2, 2, 3)
3
12


In [24]:
# np.empty()

arr = np.empty((4, 3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12


In [26]:
# np.empty_like()

arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

arr = np.empty_like(arr3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
int64
(2, 2, 3)
3
12


In [27]:
# np.full()

arr = np.full((4, 3), 10)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
<class 'numpy.ndarray'>
int64
(4, 3)
2
12


In [31]:
arr = np.full((4, 3), True)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
<class 'numpy.ndarray'>
bool
(4, 3)
2
12


In [32]:
arr = np.full((4, 3), np.inf)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12


In [35]:
# np.full_like()

arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

arr = np.full_like(arr3, 10)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]]]
<class 'numpy.ndarray'>
int64
(2, 2, 3)
3
12


In [36]:

arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

arr = np.full_like(arr3, np.inf, dtype=np.float64)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
<class 'numpy.ndarray'>
float64
(2, 2, 3)
3
12


### Array Creation With Random Values

In [39]:
# np.random.rand(shape)

arr = np.random.rand(2,3)  # 0 to 1 random values

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.5259446  0.3225481  0.37237641]
 [0.30478166 0.88592479 0.1383699 ]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [45]:
# np.random.randint(starting point, end point, shape)

arr = np.random.randint(1, 10, (2,3))  # 0 to 1 random values

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[9 4 4]
 [8 6 3]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [44]:

arr = np.random.randint(1, 10, (2,))  # 1d array

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[5 9]
<class 'numpy.ndarray'>
int32
(2,)
1
2


In [48]:
# np.random.uniform(starting point, end point, shape)    #floating type

arr = np.random.uniform(1, 100, (3, 2, 3)) 

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[41.77605521 98.4210094  99.85467496]
  [61.35466145 61.88053867 83.05323519]]

 [[37.37056956  3.78975739 61.98542946]
  [69.73491941 39.53820408  2.24448534]]

 [[57.37115189 77.85417528 55.26436906]
  [ 1.0202543  78.53563175 14.86144384]]]
<class 'numpy.ndarray'>
float64
(3, 2, 3)
3
18


### Array Creation From Range

In [49]:
# np.arange(first, end, step)   -> similar to range function

arr = np.arange(1, 10, 2)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 3 5 7 9]
<class 'numpy.ndarray'>
int64
(5,)
1
5


In [53]:
#reshape the np.arange()

arr = np.arange(1, 10, 1).reshape(3, 3)

#mat = arr.reshape(3, 3)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2
9


In [57]:
# np.linspace(start, end, amount)

arr = np.linspace(1, 10, 11) # it will divide with 0.9 evenly

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]
<class 'numpy.ndarray'>
float64
(11,)
1
11


In [58]:
# np.logspace(start, end, amount)

arr = np.logspace(1, 10, 11)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1.00000000e+01 7.94328235e+01 6.30957344e+02 5.01187234e+03
 3.98107171e+04 3.16227766e+05 2.51188643e+06 1.99526231e+07
 1.58489319e+08 1.25892541e+09 1.00000000e+10]
<class 'numpy.ndarray'>
float64
(11,)
1
11


In [59]:
# np.logspace(start, end, amount)

arr = np.logspace(0, 4, 6, base=2)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


### Diagonal Matrix

In [7]:
diagonal_matrix = np.diag([1, 2, 3])
print(diagonal_matrix)


[[1 0 0]
 [0 2 0]
 [0 0 3]]


### Identity Matrix

In [8]:
identity_mat = np.eye(3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
identity_mat = np.eye(2,3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]]


In [11]:
identity_mat = np.eye(2,3, -1)  # row, col, k
print(identity_mat)

[[0. 0. 0.]
 [1. 0. 0.]]


In [12]:
identity_mat = np.eye(2,3, 1)  # row, col, k
print(identity_mat)

[[0. 1. 0.]
 [0. 0. 1.]]


### Indexing and Slicing

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

arr1[2] = 100
print(arr1)

[  1   2 100   4   5]


In [4]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2[0][1])

2


In [8]:
#slicing  [start:end:step]

arr1 = arr1[0:3]
print(arr1)

[  1   2 100]


In [23]:
# arr[row_start : row_end : step , col_start : col_end : col_step]

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

row_0 = arr2[0:1, ]
print(row_0)

row_1 = arr2[1: , ]
print(row_1)


col_0 = arr2[::, 0 : 1]
print(col_0)

col_1 = arr2[::, 1 : 2]
print(col_1)

col_2 = arr2[::, 2::]
print(col_2)

[[1 2 3]]
[[4 5 6]]
[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [24]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

portion = arr2[::, 0:2]
print(portion)

[[1 2]
 [4 5]]


In [28]:
# copy

arr1 = np.array([1, 2, 3, 4, 5])

arr1_mod = arr1[0:3].copy()
arr1_mod[1] = 100

print(arr1)
print(arr1_mod)

#this way it won't change the main array

[1 2 3 4 5]
[  1 100   3]


### Advanced Indexing

In [32]:
lst = np.array([1, 2, 3, 4, 5])
print(lst[[1, 3, 4]])

[2 4 5]


In [36]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2[[0,1], [1,2]])

[2 6]


In [37]:
# values greater than 2 in array 2
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2[arr2>2])

[3 4 5 6]


In [38]:
#using boolean

arr2[arr2>2] = 0
print(arr2)

[[1 2 0]
 [0 0 0]]


In [40]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

#iteration 
for x in arr2:
    print(x)

[1 2 3]
[4 5 6]


In [42]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

#iteration 
for i in arr2:
    for j in i:
        print(j)

1
2
3
4
5
6


In [43]:
# nditerator

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

#iteration 
for i in np.nditer(arr2):
    print(i)

1
2
3
4
5
6


### You have a list of temperatures recorded in Celsius. Your task is to:
#### Create a NumPy array from the given list.
#### Convert all temperatures from Celsius to Fahrenheit. The formula is F = C* 1.8 + 32.
#### Print the new Fahrenheit array.

In [47]:
import numpy as np

nump_arr = np.array([38, 32, 28, 40, 41])

fahrenheit_scale = nump_arr * 1.8 + 32
print(fahrenheit_scale)

[100.4  89.6  82.4 104.  105.8]


### You have a Python list containing the lap times (in seconds) for an athlete.

### Task:

#### Convert the list into a NumPy array.
#### Print the array's shape, size, and data type.
#### The athlete wants to see their times in minutes. Create a new array by dividing all the lap times by 60.
#Print the new array of lap times in minutes.
